#include "mem/cache/prefetch/lmhint.hh"

#include <algorithm>
#include <cstring>
#include <fstream>
#include <iterator>
#include <limits>
#include <vector>

#include "base/logging.hh"
#include "base/trace.hh"
#include "debug/HWPrefetch.hh"
#include "params/LMHintPrefetcher.hh"
#include "sim/system.hh"
#include "sim/process.hh"
#include "cpu/thread_context.hh"

namespace gem5
{

namespace prefetch
{

namespace
{

constexpr uint32_t LMHintMagic = 0x54484d4c;
constexpr uint16_t LMHintVersion = 1;
constexpr uint16_t LMHintEntrySize = 16;

uint16_t
readLe16(const uint8_t *p)
{
    return uint16_t(p[0]) | (uint16_t(p[1]) << 8);
}

uint32_t
readLe32(const uint8_t *p)
{
    return uint32_t(p[0]) | (uint32_t(p[1]) << 8) |
        (uint32_t(p[2]) << 16) | (uint32_t(p[3]) << 24);
}

uint64_t
readLe64(const uint8_t *p)
{
    uint64_t value = 0;
    for (int i = 7; i >= 0; --i) {
        value = (value << 8) | p[i];
    }
    return value;
}

std::vector<uint8_t>
readFile(const std::string &path)
{
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        return {};
    }
    return std::vector<uint8_t>(std::istreambuf_iterator<char>(in),
                                std::istreambuf_iterator<char>());
}

} // anonymous namespace

LMHintPrefetcher::LMHintStats::LMHintStats(statistics::Group *parent)
    : statistics::Group(parent, "lmhint"),
      ADD_STAT(tableEntries, statistics::units::Count::get(),
               "Number of LMHint entries loaded"),
      ADD_STAT(tableHits, statistics::units::Count::get(),
               "Demand accesses with a matching LMHint PC entry"),
      ADD_STAT(tableMisses, statistics::units::Count::get(),
               "Demand accesses without a matching LMHint PC entry"),
      ADD_STAT(noPc, statistics::units::Count::get(),
               "Demand accesses without a PC"),
      ADD_STAT(noPrefetchHints, statistics::units::Count::get(),
               "LMHint entries selecting NoPrefetch"),
      ADD_STAT(generated, statistics::units::Count::get(),
               "Prefetch candidates generated by LMHint")
{
}

LMHintPrefetcher::LMHintPrefetcher(const LMHintPrefetcherParams &p)
    : Queued(p), lmHintStats(this), hintTableFile(p.hint_table_file),
      fallbackDistance(p.fallback_distance)
{
}

void
LMHintPrefetcher::startup()
{
    Queued::startup();
    loadHintTable();
}

LMHintPrefetcher::Hint
LMHintPrefetcher::decodeHint(uint16_t raw)
{
    Hint hint;
    hint.raw = raw;
    hint.pfSel = static_cast<PrefetcherSel>((raw >> 6) & 0xf);
    hint.degree = ((raw >> 4) & 0x3) + 1;
    hint.filter = static_cast<PrefetcherSel>(raw & 0xf);
    if (hint.degree > 3) {
        hint.degree = 3;
    }
    return hint;
}

const char *
LMHintPrefetcher::prefetcherName(PrefetcherSel sel)
{
    switch (sel) {
      case PrefetcherSel::NoPrefetch:
        return "NoPrefetch";
      case PrefetcherSel::StridePrefetcher:
        return "StridePrefetcher";
      case PrefetcherSel::TaggedPrefetcher:
        return "TaggedPrefetcher";
      case PrefetcherSel::IndirectMemoryPrefetcher:
        return "IndirectMemoryPrefetcher";
      case PrefetcherSel::SignaturePathPrefetcherV2:
        return "SignaturePathPrefetcherV2";
      case PrefetcherSel::AMPMPrefetcher:
        return "AMPMPrefetcher";
      case PrefetcherSel::DCPTPrefetcher:
        return "DCPTPrefetcher";
      case PrefetcherSel::SBOOEPrefetcher:
        return "SBOOEPrefetcher";
      case PrefetcherSel::SmsPrefetcher:
        return "SmsPrefetcher";
      case PrefetcherSel::BOPPrefetcher:
        return "BOPPrefetcher";
      default:
        return "Unknown";
    }
}

std::string
LMHintPrefetcher::autoDetectHintTableFile() const
{
    if (!hintTableFile.empty()) {
        return hintTableFile;
    }

    if (!system) {
        return "";
    }

    for (auto *tc : system->threads) {
        if (!tc || !tc->getProcessPtr()) {
            continue;
        }
        const char *prog = tc->getProcessPtr()->progName();
        if (prog && prog[0] != 0) {
            return std::string(prog);
        }
    }

    return "";
}

void
LMHintPrefetcher::loadHintTable()
{
    if (loadAttempted) {
        return;
    }
    loadAttempted = true;

    const std::string table_file = autoDetectHintTableFile();
    if (table_file.empty()) {
        fatal("%s: could not auto-detect workload ELF for LMHint\n", name()); // warn("%s: could not auto-detect workload ELF; LMHint disabled\n", name());
        return;
    }

    if (loadElfHintTable(table_file)) {
        lmHintStats.tableEntries += hints.size();
        inform("%s: loaded %llu LMHint entries from %s\n",
               name(), static_cast<unsigned long long>(hints.size()), table_file);
        for (const auto &hint : hints) {
            inform("%s: LMHint pc_offset=%#x sel=%s degree=%u filter=%s raw=%#x\n",
                   name(), hint.first, prefetcherName(hint.second.pfSel),
                   hint.second.degree, prefetcherName(hint.second.filter),
                   hint.second.raw);
        }
        return;
    }
    else warn("%s: could not auto-detect workload ELF; LMHint disabled\n", name());

    return;
}

// Load a raw LMHint table from a file. The file is expected to contain, just mimic now
//We need load the .lmhint section into simulated memory the next step, but for now we just read the file and parse it.

bool
LMHintPrefetcher::loadElfHintTable(const std::string &path)
{

    const auto bytes = readFile(path); // read file into bytes
    //check elf header, only support 64-bit little-endian elf files
    if (bytes.size() < 64 || std::memcmp(bytes.data(), "\177ELF", 4) != 0) {
        return false;
    }
    if (bytes[4] != 2 || bytes[5] != 1) {
        warn("%s: only 64-bit little-endian ELF hint files are supported\n",
             name());
        return false;
    }
    
    const uint64_t shoff = readLe64(&bytes[40]);
    const uint16_t shentsize = readLe16(&bytes[58]);
    const uint16_t shnum = readLe16(&bytes[60]);
    const uint16_t shstrndx = readLe16(&bytes[62]);
    if (shoff == 0 || shentsize < 64 || shnum == 0 || shstrndx >= shnum) {
        return false;
    }
    if (shoff + uint64_t(shentsize) * shnum > bytes.size()) {
        return false;
    }

    const uint8_t *shstr = &bytes[shoff + uint64_t(shentsize) * shstrndx];
    const uint64_t shstrOff = readLe64(shstr + 24);
    const uint64_t shstrSize = readLe64(shstr + 32);
    if (shstrOff + shstrSize > bytes.size()) {
        return false;
    }

    for (uint16_t i = 0; i < shnum; ++i) {
        const uint8_t *sh = &bytes[shoff + uint64_t(shentsize) * i];
        const uint32_t nameOff = readLe32(sh);
        const uint64_t sectionFlags = readLe64(sh + 8);
        const uint64_t sectionAddr = readLe64(sh + 16);
        const uint64_t sectionOff = readLe64(sh + 24);
        const uint64_t sectionSize = readLe64(sh + 32);
        if (nameOff >= shstrSize || sectionOff + sectionSize > bytes.size()) {
            continue;
        }

        const char *sectionName =
            reinterpret_cast<const char *>(&bytes[shstrOff + nameOff]);
        if (std::strcmp(sectionName, ".lmhint") != 0) {
            continue;
        }
        if (std::strcmp(sectionName, ".lmhint") == 0) {
            inform("%s: .lmhint section: file offset=0x%llx, virtual addr=0x%llx, "
                    "file size=0x%llx, flags=0x%llx\n",
                    name(),
                    static_cast<unsigned long long>(sectionOff),
                    static_cast<unsigned long long>(sectionAddr),
                    static_cast<unsigned long long>(sectionSize),
                    static_cast<unsigned long long>(sectionFlags));
        }

        std::vector<uint8_t> payload(bytes.begin() + sectionOff,
                                     bytes.begin() + sectionOff + sectionSize);
        return parseHintPayload(payload, path + "(.lmhint)");
    }

    return false;
}

bool
LMHintPrefetcher::parseHintPayload(const std::vector<uint8_t> &payload,
                                   const std::string &source)
{
    if (payload.size() < 24 || readLe32(payload.data()) != LMHintMagic) {
        return false;
    }

    const uint16_t version = readLe16(payload.data() + 4);
    const uint16_t entrySize = readLe16(payload.data() + 6);
    if (version != LMHintVersion || entrySize != LMHintEntrySize) {
        warn("%s: unsupported LMHint table in %s "
             "(version=%u entry_size=%u)\n",
             name(), source, version, entrySize);
        return false;
    }

    textBase = readLe64(payload.data() + 8);
    const uint64_t numEntries = readLe64(payload.data() + 16);
    const uint64_t needed = 24 + numEntries * uint64_t(entrySize);
    if (needed > payload.size()) {
        warn("%s: truncated LMHint table in %s\n", name(), source);
        return false;
    }

    hints.clear();
    for (uint64_t i = 0; i < numEntries; ++i) {
        const uint8_t *entry = payload.data() + 24 + i * entrySize;
        const Addr pcOffset = readLe64(entry);
        const uint16_t raw = readLe16(entry + 8);
        hints[pcOffset] = decodeHint(raw);
    }
    return true;
}


void
LMHintPrefetcher::calculatePrefetch(const PrefetchInfo &pfi,
    std::vector<AddrPriority> &addresses, const CacheAccessor &cache)
{
    if (!pfi.hasPC()) {
        lmHintStats.noPc++;
        return;
    }

    const Addr pc = pfi.getPC();
    if (pc < textBase) {
        lmHintStats.tableMisses++;
        return;
    }

    
    const Addr pcOffset = pc - textBase;
    DPRINTF(HWPrefetch, "LMHint pc=%#x pc_offset=%#x addr=%#x \n",
            pc, pcOffset, pfi.getAddr());


    auto it = hints.find(pcOffset);
    if (it == hints.end()) {
        lmHintStats.tableMisses++;
        return;
    }

    lmHintStats.tableHits++;
    const Hint &hint = it->second;

    DPRINTF(HWPrefetch, "LMHint pc=%#x pc_offset=%#x addr=%#x "
            "sel=%s degree=%u filter=%s raw=%#x \n",
            pc, pcOffset, pfi.getAddr(), prefetcherName(hint.pfSel),
            hint.degree, prefetcherName(hint.filter), hint.raw);

    switch (hint.pfSel) {
      case PrefetcherSel::NoPrefetch:
        lmHintStats.noPrefetchHints++;
        return;
      case PrefetcherSel::StridePrefetcher:
      case PrefetcherSel::IndirectMemoryPrefetcher:
      case PrefetcherSel::SignaturePathPrefetcherV2:
      case PrefetcherSel::DCPTPrefetcher:
      case PrefetcherSel::TaggedPrefetcher:
      case PrefetcherSel::AMPMPrefetcher:
      case PrefetcherSel::SBOOEPrefetcher:
      case PrefetcherSel::SmsPrefetcher:
      case PrefetcherSel::BOPPrefetcher:
      default:
        warn_once("%s: unknown LMHint prefetcher selection code in raw hint "
                  "%#x; ignoring\n", name(), hint.raw);
        return;
    }

    lmHintStats.generated += addresses.size();
}

} // namespace prefetch
} // namespace gem5
